CREATE TABLE IF NOT EXISTS tm_category(id VARCHAR(40) PRIMARY KEY,name VARCHAR(80),sort INT);
CREATE TABLE IF NOT EXISTS tm_venue(id VARCHAR(40) PRIMARY KEY,name VARCHAR(150) NOT NULL,city VARCHAR(60) NOT NULL,address VARCHAR(300) NOT NULL,longitude DOUBLE,latitude DOUBLE,description VARCHAR(1000),images TEXT);
CREATE TABLE IF NOT EXISTS tm_event(id VARCHAR(40) PRIMARY KEY,category_id VARCHAR(40) NOT NULL,venue_id VARCHAR(40) NOT NULL,title VARCHAR(180) NOT NULL,description TEXT,cover VARCHAR(500),images TEXT,status VARCHAR(30) NOT NULL,refund_allowed BOOLEAN DEFAULT FALSE,refund_deadline BIGINT,theme VARCHAR(30) DEFAULT 'violet',created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS tm_session(id VARCHAR(40) PRIMARY KEY,event_id VARCHAR(40) NOT NULL,name VARCHAR(120),start_at BIGINT NOT NULL,end_at BIGINT NOT NULL,entry_start BIGINT NOT NULL,entry_end BIGINT NOT NULL,capacity INT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_session_event ON tm_session(event_id);
CREATE TABLE IF NOT EXISTS tm_ticket_type(id VARCHAR(40) PRIMARY KEY,session_id VARCHAR(40) NOT NULL,name VARCHAR(80) NOT NULL,price_cent BIGINT NOT NULL,stock_total INT NOT NULL,sale_start BIGINT NOT NULL,sale_end BIGINT NOT NULL,status VARCHAR(20) NOT NULL);
CREATE TABLE IF NOT EXISTS tm_stock(ticket_type_id VARCHAR(40) PRIMARY KEY,available INT NOT NULL);
