CREATE TABLE IF NOT EXISTS tm_user(id VARCHAR(40) PRIMARY KEY,email VARCHAR(254) NOT NULL UNIQUE,nick_name VARCHAR(80) NOT NULL,icon VARCHAR(500) DEFAULT '',role VARCHAR(20) DEFAULT 'USER',created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS tm_user_info(user_id VARCHAR(40) PRIMARY KEY,city VARCHAR(80),introduce VARCHAR(200),birthday VARCHAR(30));
CREATE TABLE IF NOT EXISTS tm_staff_session(user_id VARCHAR(40),session_id VARCHAR(40),PRIMARY KEY(user_id,session_id));

